### ISSUE TITLE
Demo cho một request cho phía server

### ISSUE THREAD

**Issue by TranNgocKhoa** [TranNgocKhoa/newstar-angular-fe#1]
Team server viết cái api cho tụi tao nhận danh sách category coi. Không lấy được thì sao mà xài đây????

**Comment by 15110150** [comment]
anh ơi, viết giùm e mấy cái api lấy danh sách category cha con giùm cái

**Comment by TranNgocKhoa** [comment]
> anh ơi, viết giùm e mấy cái api lấy danh sách category cha con giùm cái

Lúc chọn cha và con, 
Mỗi lần click chọn con thì danh sách cha con sẽ bị thay đổi, do ràng buộc cha con. Ví dụ là con thì không thể làm cha được. Làm cha rồi thì không làm con được.
Mỗi lần vậy thì sẽ phải gửi lên server cái category đang được tạo để server nắm thông tin. Sau đó mới gửi về được.

**Comment by TranNgocKhoa** [comment]
Đã xong. Check lại đi nha
